import logging

from odoo import api, fields, models  # type: ignore

_logger = logging.getLogger(__name__)


class SaleOrder(models.Model):
    _inherit = 'sale.order'

    # ------------------------------------------------------------------
    # Shipping & Tracking (Feature 3)
    # ------------------------------------------------------------------
    carrier_id = fields.Many2one(
        'medical.carrier', string='Shipping Carrier',
        help='The carrier handling this delivery.',
    )
    tracking_reference = fields.Char(
        string='Tracking Reference',
        help='The carrier-issued tracking number / AWB / consignment number.',
    )
    tracking_url = fields.Char(
        string='Tracking URL',
        compute='_compute_tracking_url',
        store=False,
        help='Generated by substituting the tracking reference into the carrier URL template.',
    )

    @api.depends('carrier_id', 'carrier_id.tracking_url_template', 'tracking_reference')
    def _compute_tracking_url(self):
        for order in self:
            template = order.carrier_id.tracking_url_template if order.carrier_id else False
            ref = order.tracking_reference
            if template and ref:
                order.tracking_url = template.replace('{tracking_id}', ref)
            else:
                order.tracking_url = False

    # ------------------------------------------------------------------
    # Reviews (Feature 5)
    # ------------------------------------------------------------------
    has_been_reviewed = fields.Boolean(
        string='Has Been Reviewed',
        default=False,
        copy=False,
        index=True,
        help='Set permanently to True once the buyer submits a review. '
             'Never reset — enforces the one-time-ever review policy even if '
             'the review record itself is later deleted.',
    )
    review_ids = fields.One2many(
        'medical.order.review', 'sale_order_id', string='Reviews',
    )

    # ------------------------------------------------------------------
    # Existing: quotation notification (unchanged)
    # ------------------------------------------------------------------
    def write(self, vals):
        # Capture which orders are transitioning INTO 'sent' before the
        # write actually happens, so we notify exactly once per real
        # draft → sent transition.
        newly_quoted = self.env['sale.order']
        if vals.get('state') == 'sent':
            newly_quoted = self.filtered(lambda o: o.state != 'sent')

        res = super().write(vals)

        for order in newly_quoted:
            order._send_quotation_notification()

        return res

    def _send_quotation_notification(self):
        template = self.env.ref(
            'medical_marketplace.email_template_rfq_quoted', raise_if_not_found=False
        )
        if not template:
            _logger.warning(
                "RFQ-quoted email template not found (medical_marketplace."
                "email_template_rfq_quoted) — skipping notification for %s",
                self.name,
            )
            return
        if not self.partner_id.email:
            _logger.warning(
                "Partner %s has no email on file — skipping RFQ notification for %s",
                self.partner_id.name, self.name,
            )
            return
        template.sudo().send_mail(self.id, force_send=True)
        _logger.info("Sent RFQ-quoted notification for %s to %s", self.name, self.partner_id.email)